runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: api                    # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG
  log_file: log/api.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7

db:
  username: root
  password: 123456
  addr: 127.0.0.1
  port: 3307
  name: db_api

docker_db:
  username: root
  password: 123456
  addr: 127.0.0.1
  port: 3307
  name: db_api